import Product from "@/app/types/Product";

const products: Product[] = [
    new Product("00001", "Foundation for transparent Glow"),
    new Product("00002", "Natural Radiant Longwear Foundation"),
    new Product("00003", "ORGASM THRILLS LIP & CHEEK SET"),
    new Product("00004", "AFTERGLOW IRRESISTIBLE EYESHADOW PALETTE"),
    new Product("00005", "AIR MATTE LIP COLOR"),
    new Product("00006", "LIQUID BLUSH"),
    new Product("00007", "VOYAGEUR EYESHADOW PALETTE"),
    new Product("00008", "LIPSTICK"),
    new Product("00009", "LUNAR NEW YEAR LIGHT REFLECTING™ SETTING POWDER SET"),
    new Product("00101", "Estée Lauder Sabyasachi Limited Edition Lipstick"),
    new Product(
        "00102",
        "Futurist Aqua Brilliance™ Makeup with Intense Moisture Infusion SPF 20"
    ),
    new Product(
        "00103",
        "Double Wear Stay-in-Place Matte Powder Foundation SPF 10"
    ),
    new Product("00104", "RE-NUTRIV THE DIAMOND SERUM LIPCOLOR"),
    new Product(
        "00105",
        "Futurist Soft Touch Brightening Skincealer Concealer"
    ),
    new Product("00106", "Futurist Peptide-Power Serum Primer"),
    new Product(
        "00107",
        "Turbo Lash Travel Size High Powered Volume + Length Mascara"
    ),
    new Product("00108", "Futurist Aqua Brilliance Watery Glow Primer"),
    new Product("00109", "1Pure Color Envy Lip Oil-Serum"),
    new Product(
        "00110",
        "Bronze Goddess Flora Verde Palette for Eyes & Cheeks"
    ),
    new Product("00201", "ROUGE VOLUPTE SHINE"),
    new Product("00202", "MASCARA VOLUME EFFET FAUX CILS"),
    new Product("00203", "TOUCHE ECLAT LE TEINT"),
    new Product("00204", "ROUGE PUR COUTURE THE SLIM"),
    new Product("00205", "SATIN CRUSH EYESHADOWS"),
    new Product("00206", "ALL HOURS FOUNDATION"),
    new Product("00207", "TATOUAGE COUTURE VELVET CREAM LIQUID LIPSTICK"),
    new Product("00208", "LASH CLASH EXTREME VOLUME MASCARA"),
    new Product("00209", "ALL HOURS HYPER FINISH"),
    new Product("00210", "1ALL HOURS CONCEALER"),

    new Product("00301", "Make-up Foundation 0.5.N Porcelain"),
    new Product("00302", "Eye care concealer 1-2R Rose Porcelain"),
    new Product("00303", "Nourishing powder 2 Light to medium"),
    new Product("00304", "Mascara Intense Black"),
    new Product("00305", "Meta Light Eyeliner 09 Polar White"),
    new Product("00306", "Unbelieva Brow 48H Gel 7.0 Blonde"),
    new Product("00307", "Lipstick  105 Beautiful Rosewood"),
    new Product("00308", "Le Lipliner 630 Beige A Nu "),
    new Product(
        "00309",
        "Lipgloss Brilliant Signature Plump-in-Gloss 400 Maximize"
    ),
    new Product(
        "00310",
        "Eyebrow pencil 24h Filling Triangular Pencil 8.0 Light Cool Blonde"
    ),

    new Product("00401", "Easy Bake Loose Baking & Setting Powder"),
    new Product("00402", "FAUX FILLER Extra Shine Lip Gloss"),
    new Product("00403", "#FauxFilter Luminous Matte Concealer"),
    new Product("00404", "#FAUXFILTER Color Corrector"),
    new Product("00405", "Lip Contour 2.0 Automatic Matte Lip Pencil"),
    new Product("00406", "Creamy Obsessions Eyeshadow Palette"),
    new Product("00407", "#FauxFilter Luminous Matte Foundation"),
    new Product("00408", "Pretty Grunge Eyeshadow Palette"),
    new Product("00409", "Life Liner Double Ended Eyeliner Liquid & Pencil"),
    new Product("00410", "GloWish Cheeky Vegan Blush Powder"),

    new Product("00501", "BABY GOT BLUSH liquid blush 10 Pinkalicious"),
    new Product("00502", "Brow lifting gel set"),
    new Product("00503", "SKIN tint 20"),
    new Product("00504", "baby got blush 10"),
    new Product("00505", "MAGIC FILTER glow booster 10 Light"),
    new Product("00506", "Hydra kiss lip oil 03 Pink Champagne"),
    new Product("00507", "Skin Lovin' SENSITIVE CONCEALER 10"),
    new Product("00508", "Harley Quinn eyeshadow palette 02 Mad Love"),
    new Product("00509", "sun club matt bronzing powder 01"),
    new Product("00510", "I LOVE EXTREME crazy volume mascara"),

    new Product("10601", "BODY Moisturizing Balm"),
    new Product("10602", "Cleanance cleansing gel"),
    new Product("10603", "HYALURON ACTIV B3 Cell renewing cream"),
    new Product("10604", "XeraCalm A.D Replenishing cream"),
    new Product("10605", "ULTRA FLUID PERFECTOR SPF 50+"),
    new Product("10606", "Sun spray SPF 50+"),
    new Product("10607", "HYALURON ACTIV B3 Plumping serum concentrate"),
    new Product("10608", "A-OXitive EYE TIGHTENING EYE CARE"),
    new Product("10609", "Cleanance MASK Peeling-Maske"),
    new Product("10610", "Cold Cream Intensiv-Handcreme"),

    new Product("10701", "Biafin Skin Emulsion"),

    new Product("10801", "HYDRAPHASE HA AUGEN"),
    new Product("10802", "HYDRAPHASE UV INTENSE LEGERE "),
    new Product("10803", "TOLERIANE DERMALLERGO CREME"),
    new Product("10804", "LIPIKARLAIT UREA 10%"),
    new Product("10805", "LIPIKAR BAUME AP+M PAPP-TUBE RÜCK- FETTENDER BALSAM"),
    new Product("10806", "ANTHELIOS AGE CORRECT LSF 50"),
    new Product("10807", "ANTHELIOS INVISIBLE FLUID LSF 30"),
    new Product("10808", "24H PHYSIOLOGICAL DEODORANT ROLL-ON"),
    new Product("10809", "EFFACLAR HIGHLY CONCENTRATED SERUM"),
    new Product("10810", "CICAPLAST BAUME B5+"),

    new Product(
        "10901",
        "1.	DermatoClean [Hyaluron] Micellar cleansing fluid 3 in 1"
    ),
    new Product("10902", "DermoPure Triple Effect Cleansing gel"),
    new Product("10903", "DermoPure Triple Effect Serum"),
    new Product("10904", "DermoPure Wash scrub"),
    new Product("10905", "DermoPure Moisturizing care to accompany therapy"),
    new Product("10906", "Q10 Active Day care"),
    new Product("10907", "pH5 Ultra-light moisturizer"),
    new Product("10908", "Hyaluron filler + 3x Effect Serum concentrate"),
    new Product("10909", "Hyaluron filler + Elasticity Eye Care LSF 20"),
    new Product("10910", "Hyaluron filler + 3x Effect 5% Urea Tag"),

    new Product("11001", "Sébium Hydra"),
    new Product("11002", "Sensibio AR"),
    new Product("11003", "Sébium Serum"),
    new Product("11004", "Hydrabio Sérum"),
    new Product("11005", "Cicabio Crème"),
    new Product("11006", "Atoderm Intensive gel-crème"),
    new Product("11007", "Atoderm Baume Lèvres"),
    new Product("11008", "Sensibio Gel moussant"),
    new Product("11009", "Sensibio Defensive serum"),
    new Product("11010", "Hydrabio Crème"),

    new Product("21101", "PREMIUM The Voluptuous Cream Refill"),
    new Product("21102", "PREMIUM DAS GLOBALE SERUM"),
    new Product("21103", "PREMIUM The Silky Cream REFILL"),
    new Product("21104", "PREMIUM EYE CREAM"),
    new Product("21105", "PREMIUM THE VOLUPTUOUS CREAM"),
    new Product("21106", "PREMIUM THE SILKY CREAM"),

    new Product("21201", "TIME-FILLER EYES 5XP"),
    new Product("21202", "TIME-FILLER 5XP CREME"),
    new Product("21203", "TIME-FILLER 5XP GEL-CREME"),
    new Product("21204", "OPTIM-EYES"),
    new Product("21205", "NCEF-SHOT"),
    new Product("21206", "OXYGEN GLOW-CREME"),
    new Product("21207", "OXYGEN GLOW (EYES)"),
    new Product("21208", "OXYGEN-GLOW CC CREME"),
    new Product("21209", "NCEF-REVERSE"),
    new Product("21210", "NCEF-INTENSIVE"),

    new Product("21301", "Wrinkle Smoothing Day Emulsion SPF20"),
    new Product("21302", "Advanced Super Revitalizing Cream"),
    new Product("21303", "Intensive Firming Contour Serum"),
    new Product("21304", "Legendary Enmei Ultimate Luminance Serum"),
    new Product("21305", "Wrinkle Smoothing Cream Enriched"),
    new Product("21306", "Uplifting and Firming Day Cream SPF30"),
    new Product("21307", "Total Regenerating Cream"),
    new Product("21308", "Serum Power Infusing Concentrate"),
    new Product("21309", "LiftDefine Radiance Serum"),
    new Product("21310", "Wrinkle Smoothing Day Cream SPF25"),

    new Product("21401", "Double Serum"),
    new Product("21402", "Double Serum Eye"),
    new Product("21403", "Extra-Firming Energy - Anti-Age Daycreme"),
    new Product(
        "21404",
        "Multi-Intensive Jour - Super Intensive Anti-Age Creme"
    ),
    new Product("21405", "Total Eye Lift"),
    new Product("21406", "Multi-Active Crème Nuit Peaux sèches"),
    new Product("21407", "Multi-Active Essence de jeunesse revitalisante"),
    new Product("21408", "Extra-Firming Jour Day Cream"),
    new Product("21409", "Extra-Firming Cou & Décolleté"),
    new Product("21410", "Precious Le Sérum Lift - Serum"),
    new Product("21411", "Precious La Crème"),

    new Product("21501", 'Multi-Peptide + HA Serum ("Buffet")'),

    new Product("21502", "Multi-Peptide + Copper Peptides 1% Serum"),

    new Product("21503", "100% Organic Cold-Pressed Rose Hip Seed Oil"),
    new Product("21504", "Multi-Peptide Eye Serum"),
    new Product("21505", "Matrixyl 10% + HA"),
    new Product("21506", "Argireline Solution 10%"),
    new Product("21507", "Granactive Retinoid 5% in Squalane"),
    new Product("21508", "Retinol 0.5% in Squalane"),
    new Product(
        "21509",
        "Ascorbyl Tetraisopalmitate Solution 20% in Vitamin F"
    ),
    new Product("21510", "Vitamin C Suspension 23% + HA Spheres 2%"),
    new Product("31601", "N°5"),
    new Product("31602", "COCO"),
    new Product("31603", "COCO NOIR"),
    new Product("31604", "COCO MADEMOISELLE"),
    new Product("31605", "CHANCE EAU FRAÎCHE"),
    new Product("31606", "GABRIELLE CHANEL"),
    new Product("31607", "COCO MADEMOISELLE"),
    new Product("31608", "GARDÉNIA"),
    new Product("31609", "BOIS DES ÎLES"),
    new Product("31610", "CRISTALLE"),
    new Product("31701", "J'adore"),
    new Product("31702", "Miss Dior Rose N'Roses"),
    new Product("31703", "DIOR ADDICT"),
    new Product("31704", "PURE POISON"),
    new Product("31705", "JOY BY DIOR"),
    new Product("31706", "DIOR HOMME PARFUM"),
    new Product("31707", "SAUVAGE EAU DE PARFUM"),
    new Product("31708", "FAHRENHEIT"),
    new Product("31709", "NEW LOOK"),
    new Product("31710", "MISS DIOR EAU DE PARFUM"),

    new Product("31801", "LA VIE EST BELLE EAU DE PARFUM"),
    new Product("31802", "IDÔLE EAU DE PARFUM"),
    new Product("31803", "LA VIE EST BELLE ROSE EXTRAORDINAIRE EDP"),
    new Product("31804", "TRÉSOR EAU DE PARFUM"),
    new Product("31805", "LA NUIT TRÉSOR LE PARFUM"),
    new Product("31806", "MAISON LANCÔME ÔUD BOUQUET"),
    new Product("31807", "LA VIE EST BELLE IRIS ABSOLU"),
    new Product("31808", "MILLE ET UNE ROSES"),
    new Product("31809", "MAISON LANCÔME ROSE PEONIA"),
    new Product("31810", "MAISON LANCÔME JASMINS MARZIPANE"),

    new Product("31901", "SCANDAL POUR HOMME ABSOLU"),
    new Product("31902", "LE MALE"),
    new Product("31903", "LE BEAU LE PARFUM"),
    new Product("31904", "GAULTIR2"),
    new Product("31905", "LE MALE ELIXIR"),
    new Product("31906", "SCANDAL ABSOLU"),
    new Product("31907", "LA BELLE PARADISE GARDEN"),
    new Product("31908", "GAULTIER DIVINE"),
    new Product("31909", "LA BELLE LE PARFUM"),
    new Product("31910", "CLASSIQUE"),

    new Product("32001", "ACQUA DI GIÒ"),

    new Product("32002", "ACQUA DI GIÒ PROFONDO"),
    new Product("32003", "ARMANI CODE"),
    new Product("32004", "SÌ INTENSE"),
    new Product("32005", "Sì PASSIONE ECLAT"),
    new Product("32006", "MY WAY"),
    new Product("32007", "ACUA DI GIOIA"),
    new Product("32008", "ARMANI CODE WOMAN"),
    new Product("32009", "Nacrée THÉ YULONG SOIE DE NACRE"),
    new Product("32010", "STRONGER WITH YOU"),

    new Product("30201", "Y EAU DE PARFUM"),
    new Product("30202", "LIBRE EAU DE PARFUM INTENSE"),
    new Product("30203", "LIBRE EAU DE PARFUM"),
    new Product("30204", "BLACK OPIUM EAU DE PARFUM OVER RED"),
    new Product("30205", "BLACK OPIUM EAU DE PARFUM"),

    new Product("42101", "Phyto PHYTOPHANERE"),
    new Product(
        "42102",
        "Phyto Phytocyane Reactional Anti-Hair Loss Set For Woman"
    ),
    new Product("42103", "Phyto Phytocyane Hair Loss Treatment Men"),
    new Product(
        "42104",
        "Phyto Phtocyane Progressive Anti-Hair Loss Set For Women"
    ),

    new Product("42201", "Advanced Formula"),
    new Product("42202", "BLOATAMIN"),
    new Product("42203", "SKINTAMIN"),
    new Product("42204", "MOM"),
    new Product("42205", "GUMMY STARS"),

    new Product("42301", "Hair Loss Capsule"),
    new Product("42302", "Hair Loss Liquid"),
    new Product("42303", "Hair Loss Shampoo"),

    new Product("42401", "Hair Intensive"),
    new Product("42402", "Calcium 700"),
    new Product("42403", "Eisen + C"),
    new Product("42404", "Omega-3 1400"),
    new Product("42405", "Magnesium 400"),
    new Product("42406", "KOLLAGEN 11.000 CURCUMA + INGWER"),
    new Product("42407", "Hyaluron Boost Serum"),
    new Product("42408", "FETTBINDER"),
    new Product("42409", "Ginseng"),
    new Product("42410", "Vitamin E 600 N"),

    new Product("52501", "ANAPHASE - Ergänzungs-Shampoo gegen Haarausfall"),
    new Product(
        "52502",
        "NEOPTIDE EXPERT - Serum gegen Haarausfall & für Haarwuchs"
    ),
    new Product(
        "52503",
        "ANACAPS REACTIV - Nahrungsergänzungsmittel gegen Haarausfall"
    ),
    new Product("52504", "ANAPHASE"),
    new Product("52505", "KERACNYL Serum"),
    new Product("52506", "KKERACNYL PP+ Creme"),
    new Product("52507", "KERACNYL UV LSF50+ Fluid"),
    new Product("52508", "KERACNYL GLYCOLIC+ Anti-Mitesser Creme"),
    new Product("52509", "ARGEAL"),
    new Product("52510", "ELUTION"),
    new Product("52511", "SQUANORM Anti-Schuppen Shampoo"),

    new Product("52601", "Sérum Potentialiste Serum"),
    new Product("52602", "Gommage Apaisant Hitzeschutz"),
    new Product("52603", "Dry Scalp Serum"),
    new Product("52604", "EINZIGARTIGES PFLEGERITUAL"),
    new Product("52605", "Bain Divalent Shampoo"),
    new Product("52606", "Bain Hydra-Fortifiant Shampoo"),
    new Product("52607", "Sérum Anti-Chute Fortifiant Haarkur"),
    new Product("52608", "Cure Anti-Chute Haarkur"),
    new Product("52609", "Bain Pureté Anti-Pelliculaire"),
    new Product("52610", "Micro-Peeling Cellulaire"),

    new Product("52701", "BEURRE CORPOREL KÖRPERCREME"),
    new Product("52702", "BIOTHERM HOMME COMFORT BALM"),
    new Product("52703", "FORCE SUPREME CREAM"),
    new Product("52704", "BIOSOURCE EAU MICELLAIRE"),
    new Product("52705", "AQUASOURCE CICA NUTRI CREAM"),
    new Product("52706", "AQUA BOUNCE TAGESPFLEGE"),
    new Product("52707", "PRO-RETINOL AUGENCREME"),
    new Product("52708", "AQUASOURCE SERUM"),
    new Product("52709", "LIFE PLANKTON ELIXIR"),
    new Product("52710", "BLUE THERAPY UPLIFT DAY CREAM"),

    new Product("52801", "Anti-Blemish Solutions Clinical Clearing Gel"),
    new Product("52802", "Anti-Blemish Solutions Oil-Control Cleansing Mask"),
    new Product(
        "52803",
        "Anti-Blemish Solutions Blemish + Line Correcting Serum"
    ),
    new Product("52804", "Blackhead Solutions 7 Day Deep Pore Cleanse & Scrub"),
    new Product(
        "52805",
        "Blackhead Solutions Self-Heating Blackhead Extractor "
    ),
    new Product("52806", "Anti-Blemish Solutions Liquid Makeup"),
    new Product("52807", "Anti-Blemish Solutions Clearing Concealer"),
    new Product("52808", "Anti-Blemish Solutions Cleansing Foam"),
    new Product("52809", "Anti-Blemish Solutions Clearing Moisturizer"),
    new Product("52810", "Anti-Blemish Solutions Clarifying Lotion"),

    new Product("52901", "Feuchtigkeitsspendendes Reinigungsöl"),
    new Product(
        "52902",
        "Feuchtigkeitsspendende Gesichtscreme mit LSF 50 (LSF 30 auch erhältlich)"
    ),
    new Product("52903", "Moisturizing face cream"),
    new Product("52904", "SA Smoothing cleaning"),
    new Product("52905", "Deep pore cleaning"),
    new Product("52906", "Moisturizing lotion"),
    new Product("52907", "Regenerating eye cream"),
    new Product("52908", "Moisturizing cream"),
    new Product("52909", "SA Urea Smoothing Moisturizing Cream"),
    new Product("52910", "Ultra Repairing Balm"),
];

export default products;
